language: c
env:
  - TOOL_NAME=k9s TOOL_VERSION=0.7.12 TOOL_TEST_COMMAND='k9s version'
  - TOOL_NAME=k9s TOOL_VERSION=0.13.0 TOOL_TEST_COMMAND='k9s version'
  - TOOL_NAME=k9s TOOL_VERSION=0.14.0 TOOL_TEST_COMMAND='k9s version'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
script:
  - ./shellcheck-on-linux-only.sh
  - asdf plugin-add $TOOL_NAME ./
  - asdf list-all $TOOL_NAME
  - asdf install $TOOL_NAME $TOOL_VERSION
  - asdf global $TOOL_NAME $TOOL_VERSION
  - k9s version
os:
  - linux
  - osx
